app:
  port: 8083

database:
  host: postgres-order
  port: 5432
  user: admin
  password: admin
  name: order

redis:
  host: redis
  port: 6379
  password: admin

secret:
  jwt_secret: secret301

kafka:
  brokers:
    - kafka:9092
  topic: order.created

product:
  host: http://productfc:8081

tracing:
  endpoint: jaeger:4318
  service_name: orderfc
  enabled: true
